### ISSUE TITLE
native2 folder

### ISSUE THREAD

**Issue by tapuu** [samheather/SeprDSA#2]
Do people actually need the native2 folder for compiling, or can it be removed?

**Comment by samheather** [comment]
I don't need it, but I guess we'll need it if we ever compile on 32bit.  I'd leave it for now tbh - then we can advertise complete compatibility for other groups when we are trying to get our code taken up.

Sam

**Comment by tapuu** [comment]
Native2 folder will be removed - nobody needs it.
