### ISSUE TITLE
Timing error fully explained. (Stop messing with plane rotation, you broke it)

### ISSUE THREAD

**Issue by pauljkl** [samheather/SeprDSA#6]
Well, thanks to Jamaal insisting that his timer was flawless, he has changed the code for plane such that it has errors in it, should you wish to thank him, feel free. 

The error in his cancel function can be found on line 23 in engine.Timing and reads: 

TaskCanceller c = new TaskCanceller();

As he is recursively instantiating TaskCanceller the cancel variable is set to false, thus rendering the cancel function useless.

You're welcome and since it is Jamaal's mess, feel free to prod him into fixing this error.

**Comment by samheather** [comment]
Thank you Jamaal for breaking Plane.  Please fix it as above :)

**Comment by tapuu** [comment]
Plane rotation will be fixed as requested.

**Comment by tapuu** [comment]
Plane rotation was fixed in Commit 1bb1c8ff31fcf789ddf6be38332c5ae63a9ca72f
Timing was fixed in Commit 03e09711d1d58318c56e423b0ccfdf58e5fe3698

**Comment by samheather** [comment]
Thank you
