### ISSUE TITLE
LWJGL abstraction leaks

### ISSUE THREAD

**Issue by tapuu** [samheather/SeprDSA#7]
LWJGL should be completely hidden from classes in game, but there are references to it in lots of places. LWJGL should be completely hidden by the classes in engine.

**Comment by pauljkl** [comment]
Main needs access to initialise it, that's about the only thing using it

**Comment by tapuu** [comment]
Wrapper functions should be added to the classes in engine and game and main can initialise them from there

**Comment by samheather** [comment]
Agreed, but stop cleaning stuff up when there is still stuff to do - cleaning up comes <i>after</i> we've finished everything.  It is functional, so leave it until we've written those reports.
