### ISSUE TITLE
Functionality overlap between Physicals and Plane

### ISSUE THREAD

**Issue by tapuu** [samheather/SeprDSA#8]
Physicals is supposed to handle all physics-related logic, including things like rotational velocity.
However, a lot of this logic is currently in Plane. This needs to be moved into Physicals.

**Comment by pauljkl** [comment]
If it only used in Plane, why bother moving functionality to Physicals for no good reason

**Comment by samheather** [comment]
Agree with Paul - it's a small neatness issue - much more important for you to spend your time writing comments Jamaal.
