### ISSUE TITLE
Removing functionality required by other classes from SeprDSA

### ISSUE THREAD

**Issue by tapuu** [samheather/SeprDSA#9]
The SeprDSA class should not be imported by other classes. There should be no functionality in the SeprDSA class which is required by other classes.

**Comment by pauljkl** [comment]
Well, it makes a lot of things simpler as it gives a place to access only waypoints rather than crappily filtering through Physicals repeatedly

**Comment by tapuu** [comment]
Still needs fixing. You could put the waypoint stuff in a static variable in waypoint class or something. Nothing should depend on main. Main should only depend on things in game, things in game should only depend on each other and things iin engine, things in engine should only depend on each other and internal libraries that we are using.
